apiVersion: apps/v1
kind: Deployment
metadata:
  name: devfest-base
  labels:
    app: devfest-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devfest-base
  template:
    metadata:
      labels:
        app: devfest-base
    spec:
      containers:
        - name: devfest-base
          image: "ghcr.io/anthonydurot/devfest-2021:main"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database_credentials
                  key: username
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: database_credentials
                  key: username
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database_credentials
                  key: username