apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets
  namespace: demo-sealed-secrets
  labels:
    app: sealed-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealed-secrets
  template:
    metadata:
      labels:
        app: sealed-secrets
    spec:
      containers:
        - name: base
          image: "ghcr.io/anthonydurot/devfest-2021:main"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username