apiVersion: v1
kind: Service
metadata:
  name: injection-cicd
  labels:
    app: injection-cicd
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: injection-cicd