apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgDeQRLG9+3C9ZnhAZ+yrLo0vIUom/W2Tqev1W+wPNKTMQJL59wFzkXL/Z2o/8OxeJuPftxvCSq+pugfIhavISFOS/CEE0hryjWm0TxMNCY9FOlYYHz4FS1AIp9F8KTfh6eYsApT7jiRPhyTard2o6gt4NFzg/180annCeOjz5NPvwGS3Zhg7392aghC9g3rKj1xUnUzxfc4HQkqvSLexDRPxiePLxYCX7oy1lU4SxiLvuAdTvI8Ls6RUj4hSwFOCqDQ4iNJEHGx2/XdcFY74vgezPEHgTIu/4soyMO0ebjA9+r6G4Sq+XmHt2aFvEw+QKPPND7Sj2WUxNQdr+4IA96sm12qqnHL0G3hUGcGfUIvlhNM/NNUb8kd5zu9zAKOAog+wIGRJRq4THMlvpg0lWYDUdQbCzlPMRNIhGEuDWrlwrzksZPBXeOh3aHCIelfMSZZhM5aTaWnhSzZKucWfd/sJLYCRciWnrL6Kv8SyJaqk3r67IJPs+6gkCfoOVmr73I8x3QJCcA7Eyd1c3GrA2EkJ2wGGJ0sM1agxKDtMrRRHGa1a4/YwtUlcykytK1ULDzkuXmbS3vM7XGrWdv2geBMDnOKfccQkuBqm7f+fbXAlClEdsi902RpmkSrDH4PxmGhCuJ2BWd13eb+dca9+KXLgCdm32jTJQEAEJzaWhwBmWJCnobzqF477C3IKkXHk7YbdI2pvE7udA/+gtIHlFfhCo4=
    username: AgCXdiyYfOWTc7AhBQySUdO9UXKKbexYn9KosjnczOqp72i1FlwCI8OrZ70u9gh1grOwXHQUQ8fZWitzYPSEej5knuMFp/EOQr8YxxkYsEfxppM/29bG6PjMjWB+uUF7pN7X6BzJW6Xm6XeuE8PFBpD3pklnQQY5P4OhZrRG5RFSYLDjuUsJOd6sHiztlkwU2YG6bgE3lUrCI7Mp1IOjioi1BEd/28XcqxCcforkTtO55Is+X1nH2MkQjxhXVkJ4ZSyHaazZbpWSuhBu7JyZGtUu+e2cH0uR4VsdgtnFe69FWo5c53nygSaSAV0t37vUen2oSaX947fOmoxGtaAs/p2P6uubnFfUilCrHufzaRp38yNxz3b5nOwFvQX2jUevwTVuyM0anCNUmSrMXurxzOA84xRJ4y9YU8WHqvWl0+K9u6k0vO+9stVthGK6Ag1eNx059UZ7ioWbejOf/UNW1AeO4jErHD/LzqxJ2t3Bh7rRB89WkXZ9UwScHexlV3wDBaok67rPgtOUPKFYsIFQNSeT6MZEzHaSF6kSCRVZdZr9PCSGKt+CXcntqp05uarq5EDpLPaIqO1uN6iTDBDG5136PIqtEH8ehOrdv/up2WJC8PQnp/ft0ytucK8iJezuPOwXchULJE6OklbC20LMNcEdigoS+KkXB1vFCQgpc1ImdthsLTJ9DaOL7ZHYePtOGXhZyaYWBKb5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque

